[package]
name = "lua_module"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.71"
cli = { path = "../cli" }
mlua = { version = "0.9.1", features = ["luajit", "module", "serialize"] }
serde = { version = "1.0.193", features = ["derive"] }
