name: "Build"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["desktop", "kindle"]
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: rakuyomi
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: "nix build .#rakuyomi.${{ matrix.target }} -o build"
